# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cac1d78e474ed764ff97303fcfcd2fb5e215a12ad490e06d0cf5e4ef5fe0af70741a2b5e46c3b7ab7b3e79d8c31c7d696afbc3674fc44ee6db88831d671fa2c1

test:
  secret_key_base: b1bb54ba73cfb964723fff76190dee9dd52ea557164b9d01e8837ceca4b9e7be8f4534d23f7e3ffcf1851c0a8cbd3646f6e0e4555ee29283fc4e8ec183f3a645

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
